### ISSUE TITLE
Error Alert after restart explorer and restart PC

### ISSUE THREAD

**Issue by mahendrap1600018208** [WinTenDev/WinNetMeter#2]
![error net](https://user-images.githubusercontent.com/39918800/62059795-16ba1d80-b24e-11e9-8ec5-a8e6f1d96bcc.png)

**Comment by azhe403** [comment]
Coba langkah2 berikut pak:
1. Klik continue, 
2. Buka WinNetMeter via Start atau Desktop.
3. Pada menu General, ke bagian Network Interface pilih adapter yang di inginkan.
4. Pilih **Save**

![gambar](https://user-images.githubusercontent.com/17938038/62060264-022a5500-b24f-11e9-97b3-24c8411a79a1.png)

Coba sertakan versi yang di pakai?

**Comment by jovanzers** [comment]
@mahendrap1600018208 Sebelumnya bisa dilampirkan WinNetMeter versi berapa yang digunakan?
