### ISSUE TITLE
[BUG] An error occured when clicked Save button

### ISSUE THREAD

**Issue by AyraHikari** [WinTenDev/WinNetMeter#4]
This error when i click save button.
![image](https://user-images.githubusercontent.com/36266025/62089084-d086ad80-b291-11e9-8911-07ab92eb534a.png)
![image](https://user-images.githubusercontent.com/36266025/62088793-c1ebc680-b290-11e9-973b-c4b11c1477c3.png)

**What i have try:**
1. Reinstall
2. Re-Register Shell
3. Uninstall Shell then Re-Register Shell

**My PC:**
- Windows 10 Pro 1809 build 17763.348
- AMD A9 + R5 Radeon 2 GPUs
- 4 GB RAM
- Check first image for Network Interface

**Comment by Tosca01** [comment]
Hello AyraHikari, 
Thanks for reporting this bug.

This issue has been fixed in the latest release of WinNetMeter, you can download it in here https://github.com/WinTenDev/WinNetMeter/releases/download/v1.0.7149.24681/WinNetMeter.1.0.7149.24681.Setup.exe

**Comment by AyraHikari** [comment]
Ok thx

**Comment by AyraHikari** [comment]
Btw, another bug
https://telegra.ph/file/ff091a3a073faaa9b1fde.mp4

**Comment by Tosca01** [comment]
Okay thanks, I will try to fixed it.. 😊
