### ISSUE TITLE
Padding pada ikon taskbar

### ISSUE THREAD

**Issue by rzlamrr** [WinTenDev/WinNetMeter#8]
Ketika "use small taskbar button" diaktifkan, muncul padding dibagian bawah ikon aplikasi sehingga aplikasi terlihat mengambang. Kalau "use small taskbar button" dinonaktiflan ikon kembali normal
![IMG_20191220_141720_401](https://user-images.githubusercontent.com/46296998/71237193-73b88c00-2333-11ea-8365-66a314b80291.jpg)
![IMG_20191220_142129_444](https://user-images.githubusercontent.com/46296998/71237449-1ec94580-2334-11ea-9d6f-bb5bf43b52d8.jpg)

**Comment by Tosca01** [comment]
> Ketika "use small taskbar button" diaktifkan, muncul padding dibagian bawah ikon aplikasi sehingga aplikasi terlihat mengambang. Kalau "use small taskbar button" dinonaktiflan ikon kembali normal
> ![IMG_20191220_141720_401](https://user-images.githubusercontent.com/46296998/71237193-73b88c00-2333-11ea-8365-66a314b80291.jpg)
> ![IMG_20191220_142129_444](https://user-images.githubusercontent.com/46296998/71237449-1ec94580-2334-11ea-9d6f-bb5bf43b52d8.jpg)

Udh coba relock taskbar? klik kanan taskbar -> hilangin ceklis di lock the taskbar -> lalu ceklis lock lagi

**Comment by rzlamrr** [comment]
> > Ketika "use small taskbar button" diaktifkan, muncul padding dibagian bawah ikon aplikasi sehingga aplikasi terlihat mengambang. Kalau "use small taskbar button" dinonaktiflan ikon kembali normal
> > ![IMG_20191220_141720_401](https://user-images.githubusercontent.com/46296998/71237193-73b88c00-2333-11ea-8365-66a314b80291.jpg)
> > ![IMG_20191220_142129_444](https://user-images.githubusercontent.com/46296998/71237449-1ec94580-2334-11ea-9d6f-bb5bf43b52d8.jpg)
> 
> Udh coba relock taskbar? klik kanan taskbar -> hilangin ceklis di lock the taskbar -> lalu ceklis lock lagi

Udah gan,tetep

**Comment by Tosca01** [comment]
Baik, Thanks laporannya, WinNetMeter memang masih memiliki bug pada layout taskbar dan masih blm menemukan solusinya, InsyaAllah kedepannya akan diperbaiki..

**Comment by azhe403** [comment]
kayaknya ini karena tema nya, itu pake tema pihak ketiga?
